# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'inventory.ui'
##
## Created by: Qt User Interface Compiler version 6.6.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QDialog, QFrame,
    QGridLayout, QHBoxLayout, QHeaderView, QLabel,
    QLineEdit, QPushButton, QSizePolicy, QSpacerItem,
    QTabWidget, QTableWidgetItem, QTreeView, QVBoxLayout,
    QWidget)

from toolset.gui.dialogs.inventory import (DropFrame, InventoryTable)
from toolset.rcc import resources_rc_pyside6
class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(730, 611)
        self.verticalLayout_2 = QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.tabWidget = QTabWidget(Dialog)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.verticalLayout_3 = QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.coreSearchEdit = QLineEdit(self.tab)
        self.coreSearchEdit.setObjectName(u"coreSearchEdit")

        self.verticalLayout_3.addWidget(self.coreSearchEdit)

        self.coreTree = QTreeView(self.tab)
        self.coreTree.setObjectName(u"coreTree")
        self.coreTree.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.coreTree.setDragEnabled(True)
        self.coreTree.setDragDropMode(QAbstractItemView.DragOnly)
        self.coreTree.setDefaultDropAction(Qt.CopyAction)
        self.coreTree.setAlternatingRowColors(True)
        self.coreTree.header().setVisible(False)

        self.verticalLayout_3.addWidget(self.coreTree)

        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.verticalLayout_4 = QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.modulesSearchEdit = QLineEdit(self.tab_2)
        self.modulesSearchEdit.setObjectName(u"modulesSearchEdit")

        self.verticalLayout_4.addWidget(self.modulesSearchEdit)

        self.modulesTree = QTreeView(self.tab_2)
        self.modulesTree.setObjectName(u"modulesTree")
        self.modulesTree.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.modulesTree.setDragEnabled(True)
        self.modulesTree.setDragDropMode(QAbstractItemView.DragOnly)
        self.modulesTree.setDefaultDropAction(Qt.CopyAction)
        self.modulesTree.setAlternatingRowColors(True)
        self.modulesTree.setHeaderHidden(True)

        self.verticalLayout_4.addWidget(self.modulesTree)

        self.tabWidget.addTab(self.tab_2, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.verticalLayout_5 = QVBoxLayout(self.tab_5)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.overrideSearchEdit = QLineEdit(self.tab_5)
        self.overrideSearchEdit.setObjectName(u"overrideSearchEdit")

        self.verticalLayout_5.addWidget(self.overrideSearchEdit)

        self.overrideTree = QTreeView(self.tab_5)
        self.overrideTree.setObjectName(u"overrideTree")
        self.overrideTree.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.overrideTree.setDragEnabled(True)
        self.overrideTree.setDragDropMode(QAbstractItemView.DragOnly)
        self.overrideTree.setDefaultDropAction(Qt.CopyAction)
        self.overrideTree.setAlternatingRowColors(True)
        self.overrideTree.setHeaderHidden(True)

        self.verticalLayout_5.addWidget(self.overrideTree)

        self.tabWidget.addTab(self.tab_5, "")

        self.horizontalLayout.addWidget(self.tabWidget)

        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.tabWidget_2 = QTabWidget(Dialog)
        self.tabWidget_2.setObjectName(u"tabWidget_2")
        self.tabWidget_2.setAcceptDrops(True)
        self.tabWidget_2.setAutoFillBackground(True)
        self.tabWidget_2.setStyleSheet(u"")
        self.standardEquipmentTab = QWidget()
        self.standardEquipmentTab.setObjectName(u"standardEquipmentTab")
        self.standardEquipmentTab.setAutoFillBackground(False)
        self.standardEquipmentTab.setStyleSheet(u"background-color: black;")
        self.gridLayout_5 = QGridLayout(self.standardEquipmentTab)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.gridLayout = QGridLayout()
        self.gridLayout.setObjectName(u"gridLayout")
        self.headFrame = DropFrame(self.standardEquipmentTab)
        self.headFrame.setObjectName(u"headFrame")
        self.headFrame.setMinimumSize(QSize(64, 64))
        self.headFrame.setMaximumSize(QSize(64, 64))
        self.headFrame.setContextMenuPolicy(Qt.CustomContextMenu)
        self.headFrame.setAcceptDrops(True)
        self.headFrame.setFrameShape(QFrame.StyledPanel)
        self.headFrame.setFrameShadow(QFrame.Raised)
        self.headPicture = QLabel(self.headFrame)
        self.headPicture.setObjectName(u"headPicture")
        self.headPicture.setGeometry(QRect(0, 0, 64, 64))
        self.headPicture.setMaximumSize(QSize(64, 64))
        self.headPicture.setStyleSheet(u"background-color: none;")
        self.headPicture.setPixmap(QPixmap(u":/images/inventory/human_head.png"))
        self.headPicture.setScaledContents(True)
        self.slotPicture_3 = QLabel(self.headFrame)
        self.slotPicture_3.setObjectName(u"slotPicture_3")
        self.slotPicture_3.setGeometry(QRect(0, 0, 64, 64))
        self.slotPicture_3.setMaximumSize(QSize(64, 64))
        self.slotPicture_3.setPixmap(QPixmap(u":/images/inventory/slot.png"))
        self.slotPicture_3.setScaledContents(True)
        self.slotPicture_3.raise_()
        self.headPicture.raise_()

        self.gridLayout.addWidget(self.headFrame, 0, 1, 1, 1)

        self.beltFrame = DropFrame(self.standardEquipmentTab)
        self.beltFrame.setObjectName(u"beltFrame")
        self.beltFrame.setMaximumSize(QSize(64, 64))
        self.beltFrame.setContextMenuPolicy(Qt.CustomContextMenu)
        self.beltFrame.setAcceptDrops(True)
        self.beltFrame.setFrameShape(QFrame.StyledPanel)
        self.beltFrame.setFrameShadow(QFrame.Raised)
        self.beltPicture = QLabel(self.beltFrame)
        self.beltPicture.setObjectName(u"beltPicture")
        self.beltPicture.setGeometry(QRect(0, 0, 64, 64))
        self.beltPicture.setMaximumSize(QSize(64, 64))
        self.beltPicture.setStyleSheet(u"background-color: none;")
        self.beltPicture.setPixmap(QPixmap(u":/images/inventory/human_belt.png"))
        self.beltPicture.setScaledContents(True)
        self.slotPicture_8 = QLabel(self.beltFrame)
        self.slotPicture_8.setObjectName(u"slotPicture_8")
        self.slotPicture_8.setGeometry(QRect(0, 0, 64, 64))
        self.slotPicture_8.setMaximumSize(QSize(64, 64))
        self.slotPicture_8.setPixmap(QPixmap(u":/images/inventory/slot.png"))
        self.slotPicture_8.setScaledContents(True)
        self.slotPicture_8.raise_()
        self.beltPicture.raise_()

        self.gridLayout.addWidget(self.beltFrame, 2, 1, 1, 1)

        self.armrFrame = DropFrame(self.standardEquipmentTab)
        self.armrFrame.setObjectName(u"armrFrame")
        self.armrFrame.setMaximumSize(QSize(64, 64))
        self.armrFrame.setContextMenuPolicy(Qt.CustomContextMenu)
        self.armrFrame.setAcceptDrops(True)
        self.armrFrame.setFrameShape(QFrame.StyledPanel)
        self.armrFrame.setFrameShadow(QFrame.Raised)
        self.armrPicture = QLabel(self.armrFrame)
        self.armrPicture.setObjectName(u"armrPicture")
        self.armrPicture.setGeometry(QRect(0, 0, 64, 64))
        self.armrPicture.setMaximumSize(QSize(64, 64))
        self.armrPicture.setStyleSheet(u"background-color: none;")
        self.armrPicture.setPixmap(QPixmap(u":/images/inventory/human_forearm_r.png"))
        self.armrPicture.setScaledContents(True)
        self.slotPicture_10 = QLabel(self.armrFrame)
        self.slotPicture_10.setObjectName(u"slotPicture_10")
        self.slotPicture_10.setGeometry(QRect(0, 0, 64, 64))
        self.slotPicture_10.setMaximumSize(QSize(64, 64))
        self.slotPicture_10.setPixmap(QPixmap(u":/images/inventory/slot.png"))
        self.slotPicture_10.setScaledContents(True)
        self.slotPicture_10.raise_()
        self.armrPicture.raise_()

        self.gridLayout.addWidget(self.armrFrame, 1, 3, 1, 1)

        self.handrFrame = DropFrame(self.standardEquipmentTab)
        self.handrFrame.setObjectName(u"handrFrame")
        self.handrFrame.setMaximumSize(QSize(64, 64))
        self.handrFrame.setContextMenuPolicy(Qt.CustomContextMenu)
        self.handrFrame.setAcceptDrops(True)
        self.handrFrame.setFrameShape(QFrame.StyledPanel)
        self.handrFrame.setFrameShadow(QFrame.Raised)
        self.handrPicture = QLabel(self.handrFrame)
        self.handrPicture.setObjectName(u"handrPicture")
        self.handrPicture.setGeometry(QRect(0, 0, 64, 64))
        self.handrPicture.setMaximumSize(QSize(64, 64))
        self.handrPicture.setStyleSheet(u"background-color: none;")
        self.handrPicture.setPixmap(QPixmap(u":/images/inventory/human_hand_r.png"))
        self.handrPicture.setScaledContents(True)
        self.slotPicture_9 = QLabel(self.handrFrame)
        self.slotPicture_9.setObjectName(u"slotPicture_9")
        self.slotPicture_9.setGeometry(QRect(0, 0, 64, 64))
        self.slotPicture_9.setMaximumSize(QSize(64, 64))
        self.slotPicture_9.setPixmap(QPixmap(u":/images/inventory/slot.png"))
        self.slotPicture_9.setScaledContents(True)
        self.slotPicture_9.raise_()
        self.handrPicture.raise_()

        self.gridLayout.addWidget(self.handrFrame, 2, 3, 1, 1)

        self.handlFrame = DropFrame(self.standardEquipmentTab)
        self.handlFrame.setObjectName(u"handlFrame")
        self.handlFrame.setMaximumSize(QSize(64, 64))
        self.handlFrame.setContextMenuPolicy(Qt.CustomContextMenu)
        self.handlFrame.setAcceptDrops(True)
        self.handlFrame.setFrameShape(QFrame.StyledPanel)
        self.handlFrame.setFrameShadow(QFrame.Raised)
        self.handlPicture = QLabel(self.handlFrame)
        self.handlPicture.setObjectName(u"handlPicture")
        self.handlPicture.setGeometry(QRect(0, 0, 64, 64))
        self.handlPicture.setMaximumSize(QSize(64, 64))
        self.handlPicture.setStyleSheet(u"background-color: none;")
        self.handlPicture.setPixmap(QPixmap(u":/images/inventory/human_hand_l.png"))
        self.handlPicture.setScaledContents(True)
        self.slotPicture_7 = QLabel(self.handlFrame)
        self.slotPicture_7.setObjectName(u"slotPicture_7")
        self.slotPicture_7.setGeometry(QRect(0, 0, 64, 64))
        self.slotPicture_7.setMaximumSize(QSize(64, 64))
        self.slotPicture_7.setPixmap(QPixmap(u":/images/inventory/slot.png"))
        self.slotPicture_7.setScaledContents(True)
        self.slotPicture_7.raise_()
        self.handlPicture.raise_()

        self.gridLayout.addWidget(self.handlFrame, 2, 0, 1, 1)

        self.implantFrame = DropFrame(self.standardEquipmentTab)
        self.implantFrame.setObjectName(u"implantFrame")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.implantFrame.sizePolicy().hasHeightForWidth())
        self.implantFrame.setSizePolicy(sizePolicy)
        self.implantFrame.setMaximumSize(QSize(64, 64))
        self.implantFrame.setContextMenuPolicy(Qt.CustomContextMenu)
        self.implantFrame.setAcceptDrops(True)
        self.implantFrame.setFrameShape(QFrame.StyledPanel)
        self.implantFrame.setFrameShadow(QFrame.Raised)
        self.implantPicture = QLabel(self.implantFrame)
        self.implantPicture.setObjectName(u"implantPicture")
        self.implantPicture.setGeometry(QRect(0, 0, 64, 64))
        self.implantPicture.setMaximumSize(QSize(64, 64))
        self.implantPicture.setAcceptDrops(True)
        self.implantPicture.setStyleSheet(u"background-color: none;")
        self.implantPicture.setPixmap(QPixmap(u":/images/inventory/human_implant.png"))
        self.implantPicture.setScaledContents(True)
        self.slotPicture = QLabel(self.implantFrame)
        self.slotPicture.setObjectName(u"slotPicture")
        self.slotPicture.setGeometry(QRect(0, 0, 64, 64))
        self.slotPicture.setMaximumSize(QSize(64, 64))
        self.slotPicture.setAcceptDrops(True)
        self.slotPicture.setPixmap(QPixmap(u":/images/inventory/slot.png"))
        self.slotPicture.setScaledContents(True)
        self.slotPicture.raise_()
        self.implantPicture.raise_()

        self.gridLayout.addWidget(self.implantFrame, 0, 0, 1, 1)

        self.gauntletFrame = DropFrame(self.standardEquipmentTab)
        self.gauntletFrame.setObjectName(u"gauntletFrame")
        self.gauntletFrame.setMaximumSize(QSize(64, 64))
        self.gauntletFrame.setContextMenuPolicy(Qt.CustomContextMenu)
        self.gauntletFrame.setAcceptDrops(True)
        self.gauntletFrame.setFrameShape(QFrame.StyledPanel)
        self.gauntletFrame.setFrameShadow(QFrame.Raised)
        self.gauntletPicture = QLabel(self.gauntletFrame)
        self.gauntletPicture.setObjectName(u"gauntletPicture")
        self.gauntletPicture.setGeometry(QRect(0, 0, 64, 64))
        self.gauntletPicture.setMaximumSize(QSize(64, 64))
        self.gauntletPicture.setStyleSheet(u"background-color: none;")
        self.gauntletPicture.setPixmap(QPixmap(u":/images/inventory/human_gauntlet.png"))
        self.gauntletPicture.setScaledContents(True)
        self.slotPicture_4 = QLabel(self.gauntletFrame)
        self.slotPicture_4.setObjectName(u"slotPicture_4")
        self.slotPicture_4.setGeometry(QRect(0, 0, 64, 64))
        self.slotPicture_4.setMaximumSize(QSize(64, 64))
        self.slotPicture_4.setPixmap(QPixmap(u":/images/inventory/slot.png"))
        self.slotPicture_4.setScaledContents(True)
        self.slotPicture_4.raise_()
        self.gauntletPicture.raise_()

        self.gridLayout.addWidget(self.gauntletFrame, 0, 3, 1, 1)

        self.armorFrame = DropFrame(self.standardEquipmentTab)
        self.armorFrame.setObjectName(u"armorFrame")
        self.armorFrame.setMaximumSize(QSize(64, 64))
        self.armorFrame.setContextMenuPolicy(Qt.CustomContextMenu)
        self.armorFrame.setAcceptDrops(True)
        self.armorFrame.setFrameShape(QFrame.StyledPanel)
        self.armorFrame.setFrameShadow(QFrame.Raised)
        self.armorPicture = QLabel(self.armorFrame)
        self.armorPicture.setObjectName(u"armorPicture")
        self.armorPicture.setGeometry(QRect(0, 0, 64, 64))
        self.armorPicture.setMaximumSize(QSize(64, 64))
        self.armorPicture.setStyleSheet(u"background-color: none;")
        self.armorPicture.setPixmap(QPixmap(u":/images/inventory/human_armor.png"))
        self.armorPicture.setScaledContents(True)
        self.slotPicture_6 = QLabel(self.armorFrame)
        self.slotPicture_6.setObjectName(u"slotPicture_6")
        self.slotPicture_6.setGeometry(QRect(0, 0, 64, 64))
        self.slotPicture_6.setMaximumSize(QSize(64, 64))
        self.slotPicture_6.setPixmap(QPixmap(u":/images/inventory/slot.png"))
        self.slotPicture_6.setScaledContents(True)
        self.slotPicture_6.raise_()
        self.armorPicture.raise_()

        self.gridLayout.addWidget(self.armorFrame, 1, 1, 1, 1)

        self.armlFrame = DropFrame(self.standardEquipmentTab)
        self.armlFrame.setObjectName(u"armlFrame")
        self.armlFrame.setMaximumSize(QSize(64, 64))
        self.armlFrame.setContextMenuPolicy(Qt.CustomContextMenu)
        self.armlFrame.setAcceptDrops(True)
        self.armlFrame.setFrameShape(QFrame.StyledPanel)
        self.armlFrame.setFrameShadow(QFrame.Raised)
        self.armlPicture = QLabel(self.armlFrame)
        self.armlPicture.setObjectName(u"armlPicture")
        self.armlPicture.setGeometry(QRect(0, 0, 64, 64))
        self.armlPicture.setMaximumSize(QSize(64, 64))
        self.armlPicture.setStyleSheet(u"background-color: none;")
        self.armlPicture.setPixmap(QPixmap(u":/images/inventory/human_forearm_l.png"))
        self.armlPicture.setScaledContents(True)
        self.slotPicture_5 = QLabel(self.armlFrame)
        self.slotPicture_5.setObjectName(u"slotPicture_5")
        self.slotPicture_5.setGeometry(QRect(0, 0, 64, 64))
        self.slotPicture_5.setMaximumSize(QSize(64, 64))
        self.slotPicture_5.setPixmap(QPixmap(u":/images/inventory/slot.png"))
        self.slotPicture_5.setScaledContents(True)
        self.slotPicture_5.raise_()
        self.armlPicture.raise_()

        self.gridLayout.addWidget(self.armlFrame, 1, 0, 1, 1)


        self.gridLayout_5.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.tabWidget_2.addTab(self.standardEquipmentTab, "")
        self.naturalEquipmentTab = QWidget()
        self.naturalEquipmentTab.setObjectName(u"naturalEquipmentTab")
        self.naturalEquipmentTab.setStyleSheet(u"background-color: black;")
        self.gridLayout_2 = QGridLayout(self.naturalEquipmentTab)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.claw1Frame = DropFrame(self.naturalEquipmentTab)
        self.claw1Frame.setObjectName(u"claw1Frame")
        sizePolicy.setHeightForWidth(self.claw1Frame.sizePolicy().hasHeightForWidth())
        self.claw1Frame.setSizePolicy(sizePolicy)
        self.claw1Frame.setMaximumSize(QSize(64, 64))
        self.claw1Frame.setContextMenuPolicy(Qt.CustomContextMenu)
        self.claw1Frame.setAcceptDrops(True)
        self.claw1Frame.setFrameShape(QFrame.StyledPanel)
        self.claw1Frame.setFrameShadow(QFrame.Raised)
        self.claw1Picture = QLabel(self.claw1Frame)
        self.claw1Picture.setObjectName(u"claw1Picture")
        self.claw1Picture.setGeometry(QRect(0, 0, 64, 64))
        self.claw1Picture.setMaximumSize(QSize(64, 64))
        self.claw1Picture.setStyleSheet(u"background-color: none;")
        self.claw1Picture.setPixmap(QPixmap(u":/images/inventory/human_gauntlet.png"))
        self.claw1Picture.setScaledContents(True)
        self.slotPicture_2 = QLabel(self.claw1Frame)
        self.slotPicture_2.setObjectName(u"slotPicture_2")
        self.slotPicture_2.setGeometry(QRect(0, 0, 64, 64))
        self.slotPicture_2.setMaximumSize(QSize(64, 64))
        self.slotPicture_2.setPixmap(QPixmap(u":/images/inventory/slot.png"))
        self.slotPicture_2.setScaledContents(True)
        self.slotPicture_2.raise_()
        self.claw1Picture.raise_()

        self.gridLayout_2.addWidget(self.claw1Frame, 0, 0, 1, 1)

        self.claw2Frame = DropFrame(self.naturalEquipmentTab)
        self.claw2Frame.setObjectName(u"claw2Frame")
        self.claw2Frame.setMinimumSize(QSize(64, 64))
        self.claw2Frame.setMaximumSize(QSize(64, 64))
        self.claw2Frame.setContextMenuPolicy(Qt.CustomContextMenu)
        self.claw2Frame.setAcceptDrops(True)
        self.claw2Frame.setFrameShape(QFrame.StyledPanel)
        self.claw2Frame.setFrameShadow(QFrame.Raised)
        self.claw2Picture = QLabel(self.claw2Frame)
        self.claw2Picture.setObjectName(u"claw2Picture")
        self.claw2Picture.setGeometry(QRect(0, 0, 64, 64))
        self.claw2Picture.setMaximumSize(QSize(64, 64))
        self.claw2Picture.setStyleSheet(u"background-color: none;")
        self.claw2Picture.setPixmap(QPixmap(u":/images/inventory/human_gauntlet.png"))
        self.claw2Picture.setScaledContents(True)
        self.slotPicture_13 = QLabel(self.claw2Frame)
        self.slotPicture_13.setObjectName(u"slotPicture_13")
        self.slotPicture_13.setGeometry(QRect(0, 0, 64, 64))
        self.slotPicture_13.setMaximumSize(QSize(64, 64))
        self.slotPicture_13.setPixmap(QPixmap(u":/images/inventory/slot.png"))
        self.slotPicture_13.setScaledContents(True)
        self.slotPicture_13.raise_()
        self.claw2Picture.raise_()

        self.gridLayout_2.addWidget(self.claw2Frame, 0, 1, 1, 1)

        self.claw3Frame = DropFrame(self.naturalEquipmentTab)
        self.claw3Frame.setObjectName(u"claw3Frame")
        self.claw3Frame.setMaximumSize(QSize(64, 64))
        self.claw3Frame.setContextMenuPolicy(Qt.CustomContextMenu)
        self.claw3Frame.setAcceptDrops(True)
        self.claw3Frame.setFrameShape(QFrame.StyledPanel)
        self.claw3Frame.setFrameShadow(QFrame.Raised)
        self.claw3Picture = QLabel(self.claw3Frame)
        self.claw3Picture.setObjectName(u"claw3Picture")
        self.claw3Picture.setGeometry(QRect(0, 0, 64, 64))
        self.claw3Picture.setMaximumSize(QSize(64, 64))
        self.claw3Picture.setStyleSheet(u"background-color: none;")
        self.claw3Picture.setPixmap(QPixmap(u":/images/inventory/human_gauntlet.png"))
        self.claw3Picture.setScaledContents(True)
        self.slotPicture_11 = QLabel(self.claw3Frame)
        self.slotPicture_11.setObjectName(u"slotPicture_11")
        self.slotPicture_11.setGeometry(QRect(0, 0, 64, 64))
        self.slotPicture_11.setMaximumSize(QSize(64, 64))
        self.slotPicture_11.setPixmap(QPixmap(u":/images/inventory/slot.png"))
        self.slotPicture_11.setScaledContents(True)
        self.slotPicture_11.raise_()
        self.claw3Picture.raise_()

        self.gridLayout_2.addWidget(self.claw3Frame, 0, 2, 1, 1)

        self.frame = QFrame(self.naturalEquipmentTab)
        self.frame.setObjectName(u"frame")
        self.frame.setMaximumSize(QSize(64, 64))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)

        self.gridLayout_2.addWidget(self.frame, 1, 0, 1, 1)

        self.hideFrame = DropFrame(self.naturalEquipmentTab)
        self.hideFrame.setObjectName(u"hideFrame")
        self.hideFrame.setMaximumSize(QSize(64, 64))
        self.hideFrame.setContextMenuPolicy(Qt.CustomContextMenu)
        self.hideFrame.setAcceptDrops(True)
        self.hideFrame.setFrameShape(QFrame.StyledPanel)
        self.hideFrame.setFrameShadow(QFrame.Raised)
        self.hidePicture = QLabel(self.hideFrame)
        self.hidePicture.setObjectName(u"hidePicture")
        self.hidePicture.setGeometry(QRect(0, 0, 64, 64))
        self.hidePicture.setMaximumSize(QSize(64, 64))
        self.hidePicture.setStyleSheet(u"background-color: none;")
        self.hidePicture.setPixmap(QPixmap(u":/images/inventory/human_armor.png"))
        self.hidePicture.setScaledContents(True)
        self.slotPicture_12 = QLabel(self.hideFrame)
        self.slotPicture_12.setObjectName(u"slotPicture_12")
        self.slotPicture_12.setGeometry(QRect(0, 0, 64, 64))
        self.slotPicture_12.setMaximumSize(QSize(64, 64))
        self.slotPicture_12.setPixmap(QPixmap(u":/images/inventory/slot.png"))
        self.slotPicture_12.setScaledContents(True)
        self.slotPicture_12.raise_()
        self.hidePicture.raise_()

        self.gridLayout_2.addWidget(self.hideFrame, 1, 1, 1, 1)

        self.frame_2 = QFrame(self.naturalEquipmentTab)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setMaximumSize(QSize(64, 64))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)

        self.gridLayout_2.addWidget(self.frame_2, 1, 2, 1, 1)

        self.tabWidget_2.addTab(self.naturalEquipmentTab, "")
        self.claw1Frame.raise_()
        self.claw2Frame.raise_()
        self.claw3Frame.raise_()
        self.frame.raise_()
        self.frame_2.raise_()
        self.hideFrame.raise_()

        self.verticalLayout.addWidget(self.tabWidget_2)

        self.tabWidget_3 = QTabWidget(Dialog)
        self.tabWidget_3.setObjectName(u"tabWidget_3")
        self.contentsTab = QWidget()
        self.contentsTab.setObjectName(u"contentsTab")
        self.gridLayout_3 = QGridLayout(self.contentsTab)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.contentsTable = InventoryTable(self.contentsTab)
        if (self.contentsTable.columnCount() < 3):
            self.contentsTable.setColumnCount(3)
        __qtablewidgetitem = QTableWidgetItem()
        self.contentsTable.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.contentsTable.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.contentsTable.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        self.contentsTable.setObjectName(u"contentsTable")
        self.contentsTable.setContextMenuPolicy(Qt.CustomContextMenu)
        self.contentsTable.setFrameShape(QFrame.NoFrame)
        self.contentsTable.setDragDropMode(QAbstractItemView.DropOnly)
        self.contentsTable.setSelectionMode(QAbstractItemView.SingleSelection)
        self.contentsTable.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.contentsTable.setIconSize(QSize(48, 48))
        self.contentsTable.horizontalHeader().setStretchLastSection(True)

        self.gridLayout_3.addWidget(self.contentsTable, 0, 0, 1, 1)

        self.tabWidget_3.addTab(self.contentsTab, "")

        self.verticalLayout.addWidget(self.tabWidget_3)


        self.horizontalLayout.addLayout(self.verticalLayout)

        self.horizontalLayout.setStretch(1, 3)

        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_2.addItem(self.horizontalSpacer)

        self.okButton = QPushButton(Dialog)
        self.okButton.setObjectName(u"okButton")

        self.horizontalLayout_2.addWidget(self.okButton)

        self.cancelButton = QPushButton(Dialog)
        self.cancelButton.setObjectName(u"cancelButton")

        self.horizontalLayout_2.addWidget(self.cancelButton)


        self.verticalLayout_2.addLayout(self.horizontalLayout_2)


        self.retranslateUi(Dialog)

        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Inventory Editor", None))
        self.coreSearchEdit.setPlaceholderText(QCoreApplication.translate("Dialog", u"search...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("Dialog", u"Core Items", None))
        self.modulesSearchEdit.setPlaceholderText(QCoreApplication.translate("Dialog", u"search...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("Dialog", u"Module Items", None))
        self.overrideSearchEdit.setPlaceholderText(QCoreApplication.translate("Dialog", u"search...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QCoreApplication.translate("Dialog", u"Override Items", None))
        self.headPicture.setText("")
        self.slotPicture_3.setText("")
        self.beltPicture.setText("")
        self.slotPicture_8.setText("")
        self.armrPicture.setText("")
        self.slotPicture_10.setText("")
        self.handrPicture.setText("")
        self.slotPicture_9.setText("")
        self.handlPicture.setText("")
        self.slotPicture_7.setText("")
        self.slotPicture.setText("")
        self.gauntletPicture.setText("")
        self.slotPicture_4.setText("")
        self.armorPicture.setText("")
        self.slotPicture_6.setText("")
        self.armlPicture.setText("")
        self.slotPicture_5.setText("")
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.standardEquipmentTab), QCoreApplication.translate("Dialog", u"Standard Equipment", None))
        self.claw1Picture.setText("")
        self.slotPicture_2.setText("")
        self.claw2Picture.setText("")
        self.slotPicture_13.setText("")
        self.claw3Picture.setText("")
        self.slotPicture_11.setText("")
        self.hidePicture.setText("")
        self.slotPicture_12.setText("")
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.naturalEquipmentTab), QCoreApplication.translate("Dialog", u"Natural Equipment", None))
        ___qtablewidgetitem = self.contentsTable.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("Dialog", u"Icon", None));
        ___qtablewidgetitem1 = self.contentsTable.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("Dialog", u"ResRef", None));
        ___qtablewidgetitem2 = self.contentsTable.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("Dialog", u"Name", None));
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.contentsTab), QCoreApplication.translate("Dialog", u"Contents", None))
        self.okButton.setText(QCoreApplication.translate("Dialog", u"OK", None))
        self.cancelButton.setText(QCoreApplication.translate("Dialog", u"Cancel", None))
    # retranslateUi

