# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widgets\settings\module_designer.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(453, 548)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 433, 528))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fovSpin = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.fovSpin.setMinimum(40)
        self.fovSpin.setMaximum(160)
        self.fovSpin.setObjectName("fovSpin")
        self.verticalLayout.addWidget(self.fovSpin)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.controlsResetButton = QtWidgets.QPushButton(self.groupBox)
        self.controlsResetButton.setObjectName("controlsResetButton")
        self.horizontalLayout_3.addWidget(self.controlsResetButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setVerticalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setMinimumSize(QtCore.QSize(110, 0))
        self.label_2.setStyleSheet("QLabel:hover {\n"
"    color: #555;\n"
"}")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.moveCamera3dBindEdit = SetBindWidget(self.groupBox)
        self.moveCamera3dBindEdit.setObjectName("moveCamera3dBindEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.moveCamera3dBindEdit)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setMinimumSize(QtCore.QSize(110, 0))
        self.label_3.setStyleSheet("QLabel:hover {\n"
"    color: #555;\n"
"}")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.rotateCamera3dBindEdit = SetBindWidget(self.groupBox)
        self.rotateCamera3dBindEdit.setObjectName("rotateCamera3dBindEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.rotateCamera3dBindEdit)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setMinimumSize(QtCore.QSize(110, 0))
        self.label_4.setStyleSheet("QLabel:hover {\n"
"    color: #555;\n"
"}")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.zoomCamera3dBindEdit = SetBindWidget(self.groupBox)
        self.zoomCamera3dBindEdit.setObjectName("zoomCamera3dBindEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.zoomCamera3dBindEdit)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setMinimumSize(QtCore.QSize(110, 0))
        self.label_5.setStyleSheet("QLabel:hover {\n"
"    color: #555;\n"
"}")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.selectObject3dBindEdit = SetBindWidget(self.groupBox)
        self.selectObject3dBindEdit.setObjectName("selectObject3dBindEdit")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.selectObject3dBindEdit)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setMinimumSize(QtCore.QSize(110, 0))
        self.label_6.setStyleSheet("QLabel:hover {\n"
"    color: #555;\n"
"}")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.rotateObject3dBindEdit = SetBindWidget(self.groupBox)
        self.rotateObject3dBindEdit.setObjectName("rotateObject3dBindEdit")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.rotateObject3dBindEdit)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setMinimumSize(QtCore.QSize(110, 0))
        self.label_7.setStyleSheet("QLabel:hover {\n"
"    color: #555;\n"
"}")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.deleteObject3dBindEdit = SetBindWidget(self.groupBox)
        self.deleteObject3dBindEdit.setObjectName("deleteObject3dBindEdit")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.deleteObject3dBindEdit)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setMinimumSize(QtCore.QSize(110, 0))
        self.label_8.setStyleSheet("QLabel:hover {\n"
"    color: #555;\n"
"}")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.moveCameraToSelection3dBindEdit = SetBindWidget(self.groupBox)
        self.moveCameraToSelection3dBindEdit.setObjectName("moveCameraToSelection3dBindEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.moveCameraToSelection3dBindEdit)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setMinimumSize(QtCore.QSize(110, 0))
        self.label_9.setStyleSheet("QLabel:hover {\n"
"    color: #555;\n"
"}")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setMinimumSize(QtCore.QSize(110, 0))
        self.label_10.setStyleSheet("QLabel:hover {\n"
"    color: #555;\n"
"}")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setMinimumSize(QtCore.QSize(110, 0))
        self.label_11.setStyleSheet("QLabel:hover {\n"
"    color: #555;\n"
"}")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setMinimumSize(QtCore.QSize(110, 0))
        self.label_12.setStyleSheet("QLabel:hover {\n"
"    color: #555;\n"
"}")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.moveCameraZ3dBindEdit = SetBindWidget(self.groupBox)
        self.moveCameraZ3dBindEdit.setObjectName("moveCameraZ3dBindEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.moveCameraZ3dBindEdit)
        self.zoomCameraMM3dBindEdit = SetBindWidget(self.groupBox)
        self.zoomCameraMM3dBindEdit.setObjectName("zoomCameraMM3dBindEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.zoomCameraMM3dBindEdit)
        self.moveObjectXY3dBindEdit = SetBindWidget(self.groupBox)
        self.moveObjectXY3dBindEdit.setObjectName("moveObjectXY3dBindEdit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.moveObjectXY3dBindEdit)
        self.moveObjectZ3dBindEdit = SetBindWidget(self.groupBox)
        self.moveObjectZ3dBindEdit.setObjectName("moveObjectZ3dBindEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.moveObjectZ3dBindEdit)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.verticalLayout.addWidget(self.groupBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 12, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Field of View:"))
        self.groupBox.setTitle(_translate("Form", "Controls"))
        self.controlsResetButton.setText(_translate("Form", "Reset"))
        self.label_2.setToolTip(_translate("Form", "Reacts to mouse movement."))
        self.label_2.setText(_translate("Form", "Move Camera XY"))
        self.label_3.setToolTip(_translate("Form", "Reacts to mouse movement."))
        self.label_3.setText(_translate("Form", "Rotate Camera"))
        self.label_4.setToolTip(_translate("Form", "Reacts to mouse scrolling."))
        self.label_4.setText(_translate("Form", "Zoom Camera\n"
"(Mouse Scroll)"))
        self.label_5.setToolTip(_translate("Form", "Reacts to mouse buttons."))
        self.label_5.setText(_translate("Form", "Select Object"))
        self.label_6.setToolTip(_translate("Form", "Reacts to mouse movement."))
        self.label_6.setText(_translate("Form", "Rotate Object"))
        self.label_7.setToolTip(_translate("Form", "Reacts to keyboard input."))
        self.label_7.setText(_translate("Form", "Delete Object"))
        self.label_8.setToolTip(_translate("Form", "Reacts to keyboard input."))
        self.label_8.setText(_translate("Form", "Move Camera\n"
"to Selection"))
        self.label_9.setToolTip(_translate("Form", "Reacts to mouse movement."))
        self.label_9.setText(_translate("Form", "Zoom Camera\n"
"(Mouse Movement)"))
        self.label_10.setToolTip(_translate("Form", "Reacts to mouse scrolling."))
        self.label_10.setText(_translate("Form", "Move Object XY"))
        self.label_11.setToolTip(_translate("Form", "Reacts to mouse scrolling."))
        self.label_11.setText(_translate("Form", "Move Object Z"))
        self.label_12.setToolTip(_translate("Form", "Reacts to mouse movement."))
        self.label_12.setText(_translate("Form", "Move Camera Z"))
from toolset.gui.widgets.set_bind import SetBindWidget
