# Form implementation generated from reading ui file '..\ui\editors\nss.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.middleTopHorizLyt = QtWidgets.QHBoxLayout()
        self.middleTopHorizLyt.setObjectName("middleTopHorizLyt")
        spacerItem = QtWidgets.QSpacerItem(320, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.middleTopHorizLyt.addItem(spacerItem)

from toolset.rcc import resources_rc_pyqt6
