name: pykotor-workspace
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.8
  - pip
  - pip:
    - -e ./Libraries/PyKotor
    - -e ./Libraries/PyKotorFont
    - -e ./Libraries/PyKotorGL
    - -e ./Libraries/Utility
    - -e ./Tools/HolocronToolset
    - -e ./Tools/HoloPatcher
    - -e ./Tools/KotorDiff
    - -e ./Tools/BatchPatcher
