# Form implementation generated from reading ui file '..\ui\windows\lip_syncer.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(260, 357)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.languageSelect = QtWidgets.QComboBox(parent=Dialog)
        self.languageSelect.setObjectName("languageSelect")
        self.languageSelect.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.languageSelect)
        self.verticalLayout.addLayout(self.formLayout)
        self.audioList = QtWidgets.QListWidget(parent=Dialog)
        self.audioList.setObjectName("audioList")
        self.verticalLayout.addWidget(self.audioList)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.AddAudioButton = QtWidgets.QPushButton(parent=Dialog)
        self.AddAudioButton.setObjectName("AddAudioButton")
        self.horizontalLayout.addWidget(self.AddAudioButton)
        self.removeAudioButton = QtWidgets.QPushButton(parent=Dialog)
        self.removeAudioButton.setObjectName("removeAudioButton")
        self.horizontalLayout.addWidget(self.removeAudioButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "LLanguage:"))
        self.languageSelect.setItemText(0, _translate("Dialog", "English"))
        self.AddAudioButton.setText(_translate("Dialog", "Load MP3s"))
        self.removeAudioButton.setText(_translate("Dialog", "Remove MP3"))

from toolset.rcc import resources_rc_pyqt6
