# Form implementation generated from reading ui file '..\ui\windows\module_designer_new.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.



from toolset.rcc import resources_rc_pyqt6
