# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui\widgets\settings\application.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ApplicationSettingsWidget(object):
    def setupUi(self, ApplicationSettingsWidget):
        ApplicationSettingsWidget.setObjectName("ApplicationSettingsWidget")
        ApplicationSettingsWidget.resize(800, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(ApplicationSettingsWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(ApplicationSettingsWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 780, 580))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBoxAASettings = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBoxAASettings.setObjectName("groupBoxAASettings")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBoxAASettings)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2.addWidget(self.groupBoxAASettings)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.resetAttributesButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resetAttributesButton.sizePolicy().hasHeightForWidth())
        self.resetAttributesButton.setSizePolicy(sizePolicy)
        self.resetAttributesButton.setMaximumSize(QtCore.QSize(16777215, 50))
        self.resetAttributesButton.setObjectName("resetAttributesButton")
        self.verticalLayout_4.addWidget(self.resetAttributesButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(ApplicationSettingsWidget)
        QtCore.QMetaObject.connectSlotsByName(ApplicationSettingsWidget)

    def retranslateUi(self, ApplicationSettingsWidget):
        _translate = QtCore.QCoreApplication.translate
        ApplicationSettingsWidget.setWindowTitle(_translate("ApplicationSettingsWidget", "Application Settings"))
        self.groupBoxAASettings.setTitle(_translate("ApplicationSettingsWidget", "Experimental settings (may cause app crashes)"))
        self.resetAttributesButton.setText(_translate("ApplicationSettingsWidget", "Reset Attributes"))

from toolset.rcc import resources_rc_pyqt5
