# Form implementation generated from reading ui file 'widgets\locstring_edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_Form:
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(233, 23)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.locstringText = QtWidgets.QLineEdit(Form)
        self.locstringText.setReadOnly(True)
        self.locstringText.setObjectName("locstringText")
        self.horizontalLayout.addWidget(self.locstringText)
        self.editButton = QtWidgets.QPushButton(Form)
        self.editButton.setMaximumSize(QtCore.QSize(26, 16777215))
        self.editButton.setObjectName("editButton")
        self.horizontalLayout.addWidget(self.editButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.editButton.setText(_translate("Form", "..."))
