
################################################################################
## Form generated from reading UI file 'file_system_explorer_widget.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################
from __future__ import annotations

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_FileSystemExplorerWidget:
    def setupUi(self, FileSystemExplorerWidget):
        if not FileSystemExplorerWidget.objectName():
            FileSystemExplorerWidget.setObjectName("FileSystemExplorerWidget")
        FileSystemExplorerWidget.resize(914, 600)
        self.action_back = QAction(FileSystemExplorerWidget)
        self.action_back.setObjectName("action_back")
        self.action_forward = QAction(FileSystemExplorerWidget)
        self.action_forward.setObjectName("action_forward")
        self.action_up = QAction(FileSystemExplorerWidget)
        self.action_up.setObjectName("action_up")
        self.action_cut = QAction(FileSystemExplorerWidget)
        self.action_cut.setObjectName("action_cut")
        self.action_copy = QAction(FileSystemExplorerWidget)
        self.action_copy.setObjectName("action_copy")
        self.action_paste = QAction(FileSystemExplorerWidget)
        self.action_paste.setObjectName("action_paste")
        self.action_delete = QAction(FileSystemExplorerWidget)
        self.action_delete.setObjectName("action_delete")
        self.action_properties = QAction(FileSystemExplorerWidget)
        self.action_properties.setObjectName("action_properties")
        self.action_new_window = QAction(FileSystemExplorerWidget)
        self.action_new_window.setObjectName("action_new_window")
        self.action_open_windows_terminal = QAction(FileSystemExplorerWidget)
        self.action_open_windows_terminal.setObjectName("action_open_windows_terminal")
        self.action_close = QAction(FileSystemExplorerWidget)
        self.action_close.setObjectName("action_close")
        self.action_invert_selection = QAction(FileSystemExplorerWidget)
        self.action_invert_selection.setObjectName("action_invert_selection")
        self.action_select_none = QAction(FileSystemExplorerWidget)
        self.action_select_none.setObjectName("action_select_none")
        self.action_extra_large_icons = QAction(FileSystemExplorerWidget)
        self.action_extra_large_icons.setObjectName("action_extra_large_icons")
        self.action_medium_icons = QAction(FileSystemExplorerWidget)
        self.action_medium_icons.setObjectName("action_medium_icons")
        self.action_small_icons = QAction(FileSystemExplorerWidget)
        self.action_small_icons.setObjectName("action_small_icons")
        self.action_tiles = QAction(FileSystemExplorerWidget)
        self.action_tiles.setObjectName("action_tiles")
        self.action_content = QAction(FileSystemExplorerWidget)
        self.action_content.setObjectName("action_content")
        self.action_show_hidden_items = QAction(FileSystemExplorerWidget)
        self.action_show_hidden_items.setObjectName("action_show_hidden_items")
        self.action_exit = QAction(FileSystemExplorerWidget)
        self.action_exit.setObjectName("action_exit")
        self.action_select_all = QAction(FileSystemExplorerWidget)
        self.action_select_all.setObjectName("action_select_all")
        self.action_refresh = QAction(FileSystemExplorerWidget)
        self.action_refresh.setObjectName("action_refresh")
        self.action_large_icons = QAction(FileSystemExplorerWidget)
        self.action_large_icons.setObjectName("action_large_icons")
        self.action_list = QAction(FileSystemExplorerWidget)
        self.action_list.setObjectName("action_list")
        self.action_details = QAction(FileSystemExplorerWidget)
        self.action_details.setObjectName("action_details")
        self.action_options = QAction(FileSystemExplorerWidget)
        self.action_options.setObjectName("action_options")
        self.action_about = QAction(FileSystemExplorerWidget)
        self.action_about.setObjectName("action_about")
        self.central_widget = QWidget(FileSystemExplorerWidget)
        self.central_widget.setObjectName("central_widget")
        self.verticalLayout = QVBoxLayout(self.central_widget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.toolbar_widget = QWidget(self.central_widget)
        self.toolbar_widget.setObjectName("toolbar_widget")
        self.toolbar_widget.setMouseTracking(False)
        self.toolbar_widget.setAutoFillBackground(False)
        self.toolbar_widget.setStyleSheet("")
        self.horizontalLayout = QHBoxLayout(self.toolbar_widget)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout.setContentsMargins(6, 6, 6, 6)
        self.back_button = QToolButton(self.toolbar_widget)
        self.back_button.setObjectName("back_button")

        self.horizontalLayout.addWidget(self.back_button)

        self.forward_button = QToolButton(self.toolbar_widget)
        self.forward_button.setObjectName("forward_button")

        self.horizontalLayout.addWidget(self.forward_button)

        self.history_expander = QToolButton(self.toolbar_widget)
        self.history_expander.setObjectName("history_expander")
        font = QFont()
        font.setFamily("MS Serif")
        self.history_expander.setFont(font)
        self.history_expander.setMouseTracking(True)
        self.history_expander.setIconSize(QSize(8, 8))
        self.history_expander.setToolButtonStyle(Qt.ToolButtonIconOnly)
        self.history_expander.setAutoRaise(False)
        self.history_expander.setArrowType(Qt.DownArrow)

        self.horizontalLayout.addWidget(self.history_expander)

        self.up_button = QToolButton(self.toolbar_widget)
        self.up_button.setObjectName("up_button")

        self.horizontalLayout.addWidget(self.up_button)

        self.line = QFrame(self.toolbar_widget)
        self.line.setObjectName("line")
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)

        self.horizontalLayout.addWidget(self.line)

        self.current_folder_label = QLabel(self.toolbar_widget)
        self.current_folder_label.setObjectName("current_folder_label")

        self.horizontalLayout.addWidget(self.current_folder_label)

        self.label = QLabel(self.toolbar_widget)
        self.label.setObjectName("label")

        self.horizontalLayout.addWidget(self.label)

        self.address_bar = QLineEdit(self.toolbar_widget)
        self.address_bar.setObjectName("address_bar")
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.address_bar.sizePolicy().hasHeightForWidth())
        self.address_bar.setSizePolicy(sizePolicy)
        font1 = QFont()
        font1.setFamily("MS Shell Dlg 2")
        font1.setPointSize(8)
        font1.setBold(False)
        font1.setItalic(False)
        font1.setUnderline(False)
        font1.setWeight(50)
        font1.setStrikeOut(False)
        font1.setKerning(False)
        font1.setStyleStrategy(QFont.PreferDefault)
        self.address_bar.setFont(font1)
        self.address_bar.setCursor(QCursor(Qt.IBeamCursor))
        self.address_bar.setMouseTracking(True)
        self.address_bar.setAutoFillBackground(False)
        self.address_bar.setMaxLength(32767)
        self.address_bar.setEchoMode(QLineEdit.Normal)
        self.address_bar.setCursorPosition(0)
        self.address_bar.setDragEnabled(True)
        self.address_bar.setCursorMoveStyle(Qt.LogicalMoveStyle)
        self.address_bar.setClearButtonEnabled(True)

        self.horizontalLayout.addWidget(self.address_bar)

        self.go_button = QToolButton(self.toolbar_widget)
        self.go_button.setObjectName("go_button")
        sizePolicy1 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.go_button.sizePolicy().hasHeightForWidth())
        self.go_button.setSizePolicy(sizePolicy1)
        self.go_button.setStyleSheet("")

        self.horizontalLayout.addWidget(self.go_button)

        self.search_bar = QLineEdit(self.toolbar_widget)
        self.search_bar.setObjectName("search_bar")

        self.horizontalLayout.addWidget(self.search_bar)

        self.horizontalSpacer = QSpacerItem(0, 0, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer)

        self.horizontalLayout.setStretch(10, 1)

        self.verticalLayout.addWidget(self.toolbar_widget)

        self.breadcrumb_widget = QWidget(self.central_widget)
        self.breadcrumb_widget.setObjectName("breadcrumb_widget")
        self.horizontalLayout_2 = QHBoxLayout(self.breadcrumb_widget)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(6, 0, 6, 0)
        self.breadcrumb_bar = QWidget(self.breadcrumb_widget)
        self.breadcrumb_bar.setObjectName("breadcrumb_bar")
        self.breadcrumbLayout = QHBoxLayout(self.breadcrumb_bar)
        self.breadcrumbLayout.setObjectName("breadcrumbLayout")

        self.horizontalLayout_2.addWidget(self.breadcrumb_bar)


        self.verticalLayout.addWidget(self.breadcrumb_widget)

        self.splitter = QSplitter(self.central_widget)
        self.splitter.setObjectName("splitter")
        sizePolicy2 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy2)
        self.splitter.setOrientation(Qt.Horizontal)
        self.navigation_pane = QTreeView(self.splitter)
        self.navigation_pane.setObjectName("navigation_pane")
        self.navigation_pane.setMouseTracking(True)
        self.navigation_pane.setAcceptDrops(True)
        self.navigation_pane.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.navigation_pane.setTabKeyNavigation(True)
        self.navigation_pane.setProperty("showDropIndicator", True)
        self.navigation_pane.setDragEnabled(False)
        self.navigation_pane.setDragDropOverwriteMode(True)
        self.navigation_pane.setDragDropMode(QAbstractItemView.DropOnly)
        self.navigation_pane.setDefaultDropAction(Qt.TargetMoveAction)
        self.navigation_pane.setAlternatingRowColors(True)
        self.navigation_pane.setSelectionMode(QAbstractItemView.SingleSelection)
        self.navigation_pane.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.navigation_pane.setIconSize(QSize(16, 16))
        self.navigation_pane.setSortingEnabled(True)
        self.navigation_pane.setAnimated(True)
        self.navigation_pane.setWordWrap(False)
        self.splitter.addWidget(self.navigation_pane)
        self.navigation_pane.header().setVisible(True)
        self.navigation_pane.header().setMinimumSectionSize(39)
        self.navigation_pane.header().setProperty("showSortIndicator", True)
        self.navigation_pane.header().setStretchLastSection(True)
        self.file_list_view = QListView(self.splitter)
        self.file_list_view.setObjectName("file_list_view")
        self.file_list_view.viewport().setProperty("cursor", QCursor(Qt.ArrowCursor))
        self.file_list_view.setMouseTracking(True)
        self.file_list_view.setFocusPolicy(Qt.StrongFocus)
        self.file_list_view.setContextMenuPolicy(Qt.CustomContextMenu)
        self.file_list_view.setAcceptDrops(True)
        self.file_list_view.setFrameShape(QFrame.WinPanel)
        self.file_list_view.setFrameShadow(QFrame.Plain)
        self.file_list_view.setLineWidth(1)
        self.file_list_view.setMidLineWidth(0)
        self.file_list_view.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.file_list_view.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.file_list_view.setTabKeyNavigation(True)
        self.file_list_view.setProperty("showDropIndicator", True)
        self.file_list_view.setDragEnabled(True)
        self.file_list_view.setDragDropOverwriteMode(True)
        self.file_list_view.setDragDropMode(QAbstractItemView.DragDrop)
        self.file_list_view.setDefaultDropAction(Qt.MoveAction)
        self.file_list_view.setSelectionMode(QAbstractItemView.ExtendedSelection)
        self.file_list_view.setSelectionBehavior(QAbstractItemView.SelectItems)
        self.splitter.addWidget(self.file_list_view)

        self.verticalLayout.addWidget(self.splitter)

        self.verticalLayout.setStretch(2, 1)
        self.menu_bar = QMenuBar(FileSystemExplorerWidget)
        self.menu_bar.setObjectName("menu_bar")
        self.menu_bar.setGeometry(QRect(0, 0, 914, 21))
        self.menu_file = QMenu(self.menu_bar)
        self.menu_file.setObjectName("menu_file")
        self.menu_edit = QMenu(self.menu_bar)
        self.menu_edit.setObjectName("menu_edit")
        self.menu_view = QMenu(self.menu_bar)
        self.menu_view.setObjectName("menu_view")
        self.menu_layout = QMenu(self.menu_view)
        self.menu_layout.setObjectName("menu_layout")
        self.menu_tools = QMenu(self.menu_bar)
        self.menu_tools.setObjectName("menu_tools")
        self.menu_help = QMenu(self.menu_bar)
        self.menu_help.setObjectName("menu_help")
        self.main_tool_bar = QToolBar(FileSystemExplorerWidget)
        self.main_tool_bar.setObjectName("main_tool_bar")
        self.status_bar = QStatusBar(FileSystemExplorerWidget)
        self.status_bar.setObjectName("status_bar")
        self.status_items = QLabel(self.status_bar)
        self.status_items.setObjectName("status_items")
        self.status_items.setGeometry(QRect(0, 0, 100, 30))
        self.status_size = QLabel(self.status_bar)
        self.status_size.setObjectName("status_size")
        self.status_size.setGeometry(QRect(0, 0, 100, 30))

        self.menu_bar.addAction(self.menu_file.menuAction())
        self.menu_bar.addAction(self.menu_edit.menuAction())
        self.menu_bar.addAction(self.menu_view.menuAction())
        self.menu_bar.addAction(self.menu_tools.menuAction())
        self.menu_bar.addAction(self.menu_help.menuAction())
        self.menu_file.addAction(self.action_new_window)
        self.menu_file.addAction(self.action_open_windows_terminal)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_close)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_properties)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_options)
        self.menu_file.addAction(self.action_exit)
        self.menu_edit.addAction(self.action_cut)
        self.menu_edit.addAction(self.action_copy)
        self.menu_edit.addAction(self.action_paste)
        self.menu_edit.addAction(self.action_delete)
        self.menu_edit.addSeparator()
        self.menu_edit.addAction(self.action_select_all)
        self.menu_edit.addAction(self.action_invert_selection)
        self.menu_edit.addAction(self.action_select_none)
        self.menu_view.addAction(self.action_refresh)
        self.menu_view.addSeparator()
        self.menu_view.addAction(self.menu_layout.menuAction())
        self.menu_view.addAction(self.action_show_hidden_items)
        self.menu_layout.addAction(self.action_extra_large_icons)
        self.menu_layout.addAction(self.action_large_icons)
        self.menu_layout.addAction(self.action_medium_icons)
        self.menu_layout.addAction(self.action_small_icons)
        self.menu_layout.addAction(self.action_list)
        self.menu_layout.addAction(self.action_details)
        self.menu_layout.addAction(self.action_tiles)
        self.menu_layout.addAction(self.action_content)
        self.menu_help.addAction(self.action_about)

        self.retranslateUi(FileSystemExplorerWidget)

        QMetaObject.connectSlotsByName(FileSystemExplorerWidget)
    # setupUi

    def retranslateUi(self, FileSystemExplorerWidget):
        FileSystemExplorerWidget.setWindowTitle(QCoreApplication.translate("FileSystemExplorerWidget", "File Explorer", None))
        self.action_back.setText(QCoreApplication.translate("FileSystemExplorerWidget", "Back", None))
        self.action_forward.setText(QCoreApplication.translate("FileSystemExplorerWidget", "Forward", None))
        self.action_up.setText(QCoreApplication.translate("FileSystemExplorerWidget", "Up", None))
        self.action_cut.setText(QCoreApplication.translate("FileSystemExplorerWidget", "Cut", None))
        self.action_copy.setText(QCoreApplication.translate("FileSystemExplorerWidget", "Copy", None))
        self.action_paste.setText(QCoreApplication.translate("FileSystemExplorerWidget", "Paste", None))
        self.action_delete.setText(QCoreApplication.translate("FileSystemExplorerWidget", "Delete", None))
        self.action_properties.setText(QCoreApplication.translate("FileSystemExplorerWidget", "Properties", None))
        self.action_new_window.setText(QCoreApplication.translate("FileSystemExplorerWidget", "New Window", None))
        self.action_open_windows_terminal.setText(QCoreApplication.translate("FileSystemExplorerWidget", "Open Windows Terminal", None))
        self.action_close.setText(QCoreApplication.translate("FileSystemExplorerWidget", "Close", None))
        self.action_invert_selection.setText(QCoreApplication.translate("FileSystemExplorerWidget", "Invert Selection", None))
        self.action_select_none.setText(QCoreApplication.translate("FileSystemExplorerWidget", "Select None", None))
        self.action_extra_large_icons.setText(QCoreApplication.translate("FileSystemExplorerWidget", "Select None", None))
        self.action_medium_icons.setText(QCoreApplication.translate("FileSystemExplorerWidget", "Medium Icons", None))
        self.action_small_icons.setText(QCoreApplication.translate("FileSystemExplorerWidget", "Small Icons", None))
        self.action_tiles.setText(QCoreApplication.translate("FileSystemExplorerWidget", "Tile View", None))
        self.action_content.setText(QCoreApplication.translate("FileSystemExplorerWidget", "Content", None))
        self.action_show_hidden_items.setText(QCoreApplication.translate("FileSystemExplorerWidget", "Show Hidden Items", None))
        self.action_exit.setText(QCoreApplication.translate("FileSystemExplorerWidget", "Exit", None))
        self.action_select_all.setText(QCoreApplication.translate("FileSystemExplorerWidget", "Select All", None))
        self.action_refresh.setText(QCoreApplication.translate("FileSystemExplorerWidget", "Refresh", None))
        self.action_large_icons.setText(QCoreApplication.translate("FileSystemExplorerWidget", "Large icons", None))
        self.action_list.setText(QCoreApplication.translate("FileSystemExplorerWidget", "List", None))
        self.action_details.setText(QCoreApplication.translate("FileSystemExplorerWidget", "Details", None))
        self.action_options.setText(QCoreApplication.translate("FileSystemExplorerWidget", "Options", None))
        self.action_about.setText(QCoreApplication.translate("FileSystemExplorerWidget", "About", None))
#if QT_CONFIG(tooltip)
        self.back_button.setToolTip(QCoreApplication.translate("FileSystemExplorerWidget", "Back", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.forward_button.setToolTip(QCoreApplication.translate("FileSystemExplorerWidget", "Forward", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.history_expander.setWhatsThis(QCoreApplication.translate("FileSystemExplorerWidget", "History Expander", None))
#endif // QT_CONFIG(whatsthis)
        self.history_expander.setText("")
#if QT_CONFIG(shortcut)
        self.history_expander.setShortcut("")
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(tooltip)
        self.up_button.setToolTip(QCoreApplication.translate("FileSystemExplorerWidget", "Up", None))
#endif // QT_CONFIG(tooltip)
        self.current_folder_label.setText(QCoreApplication.translate("FileSystemExplorerWidget", "This PC", None))
        self.label.setText(QCoreApplication.translate("FileSystemExplorerWidget", ">", None))
#if QT_CONFIG(whatsthis)
        self.address_bar.setWhatsThis(QCoreApplication.translate("FileSystemExplorerWidget", "Address Bar", None))
#endif // QT_CONFIG(whatsthis)
        self.address_bar.setPlaceholderText("")
#if QT_CONFIG(whatsthis)
        self.go_button.setWhatsThis(QCoreApplication.translate("FileSystemExplorerWidget", "Go button", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(tooltip)
        self.go_button.setToolTip(QCoreApplication.translate("FileSystemExplorerWidget", "Go", None))
#endif // QT_CONFIG(tooltip)
        self.search_bar.setPlaceholderText(QCoreApplication.translate("FileSystemExplorerWidget", "Search", None))
        self.search_bar.setStyleSheet(QCoreApplication.translate("FileSystemExplorerWidget", "QLineEdit {\n"
"                      border: 1px solid #a0a0a0;\n"
"                      border-radius: 2px;\n"
"                      padding: 2px;\n"
"                      }", None))
#if QT_CONFIG(whatsthis)
        self.file_list_view.setWhatsThis(QCoreApplication.translate("FileSystemExplorerWidget", "Main File Area", None))
#endif // QT_CONFIG(whatsthis)
        self.menu_file.setTitle(QCoreApplication.translate("FileSystemExplorerWidget", "&File", None))
        self.menu_edit.setTitle(QCoreApplication.translate("FileSystemExplorerWidget", "&Edit", None))
        self.menu_view.setTitle(QCoreApplication.translate("FileSystemExplorerWidget", "&View", None))
        self.menu_layout.setTitle(QCoreApplication.translate("FileSystemExplorerWidget", "&Layout", None))
        self.menu_tools.setTitle(QCoreApplication.translate("FileSystemExplorerWidget", "&Tools", None))
        self.menu_help.setTitle(QCoreApplication.translate("FileSystemExplorerWidget", "&Help", None))
        self.main_tool_bar.setWindowTitle(QCoreApplication.translate("FileSystemExplorerWidget", "toolBar", None))
        self.status_items.setText(QCoreApplication.translate("FileSystemExplorerWidget", "0 items", None))
        self.status_size.setText(QCoreApplication.translate("FileSystemExplorerWidget", "0 bytes", None))
    # retranslateUi


