from pykotor.resource.formats.tlk.io_tlk import TLKBinaryReader as TLKBinaryReader
from pykotor.resource.formats.tlk.io_tlk import TLKBinaryWriter as TLKBinaryWriter
from pykotor.resource.formats.tlk.io_tlk_json import TLKJSONReader as TLKJSONReader
from pykotor.resource.formats.tlk.io_tlk_json import TLKJSONWriter as TLKJSONWriter
from pykotor.resource.formats.tlk.io_tlk_xml import TLKXMLReader as TLKXMLReader
from pykotor.resource.formats.tlk.io_tlk_xml import TLKXMLWriter as TLKXMLWriter
from pykotor.resource.formats.tlk.tlk_auto import bytes_tlk as bytes_tlk
from pykotor.resource.formats.tlk.tlk_auto import detect_tlk as detect_tlk
from pykotor.resource.formats.tlk.tlk_auto import read_tlk as read_tlk
from pykotor.resource.formats.tlk.tlk_auto import write_tlk as write_tlk
from pykotor.resource.formats.tlk.tlk_data import TLK as TLK
from pykotor.resource.formats.tlk.tlk_data import TLKEntry as TLKEntry
