# Form implementation generated from reading ui file '..\ui\widgets\locstring_edit.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(233, 23)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.locstringText = QtWidgets.QLineEdit(parent=Form)
        self.locstringText.setReadOnly(True)
        self.locstringText.setObjectName("locstringText")
        self.horizontalLayout.addWidget(self.locstringText)
        self.editButton = QtWidgets.QPushButton(parent=Form)
        self.editButton.setMaximumSize(QtCore.QSize(26, 16777215))
        self.editButton.setObjectName("editButton")
        self.horizontalLayout.addWidget(self.editButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.editButton.setText(_translate("Form", "..."))

from toolset.rcc import resources_rc_pyqt6
