# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui\widgets\texture_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(327, 359)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sectionCombo = QtWidgets.QComboBox(Form)
        self.sectionCombo.setObjectName("sectionCombo")
        self.horizontalLayout_2.addWidget(self.sectionCombo)
        self.refreshButton = QtWidgets.QPushButton(Form)
        self.refreshButton.setMinimumSize(QtCore.QSize(70, 0))
        self.refreshButton.setObjectName("refreshButton")
        self.horizontalLayout_2.addWidget(self.refreshButton)
        self.reloadButton = QtWidgets.QPushButton(Form)
        self.reloadButton.setMinimumSize(QtCore.QSize(70, 0))
        self.reloadButton.setObjectName("reloadButton")
        self.horizontalLayout_2.addWidget(self.reloadButton)
        self.horizontalLayout_2.setStretch(0, 4)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.textureLine = QtWidgets.QFrame(Form)
        self.textureLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.textureLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textureLine.setObjectName("textureLine")
        self.verticalLayout.addWidget(self.textureLine)
        self.searchEdit = QtWidgets.QLineEdit(Form)
        self.searchEdit.setObjectName("searchEdit")
        self.verticalLayout.addWidget(self.searchEdit)
        self.resourceList = QtWidgets.QListView(Form)
        self.resourceList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.resourceList.setProperty("showDropIndicator", False)
        self.resourceList.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.resourceList.setIconSize(QtCore.QSize(64, 64))
        self.resourceList.setProperty("isWrapping", True)
        self.resourceList.setResizeMode(QtWidgets.QListView.Adjust)
        self.resourceList.setLayoutMode(QtWidgets.QListView.Batched)
        self.resourceList.setGridSize(QtCore.QSize(92, 92))
        self.resourceList.setViewMode(QtWidgets.QListView.IconMode)
        self.resourceList.setUniformItemSizes(True)
        self.resourceList.setObjectName("resourceList")
        self.verticalLayout.addWidget(self.resourceList)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.refreshButton.setToolTip(_translate("Form", "Refresh this list."))
        self.refreshButton.setText(_translate("Form", "Refresh"))
        self.reloadButton.setToolTip(_translate("Form", "Reload the active module/folder."))
        self.reloadButton.setText(_translate("Form", "Reload"))
        self.searchEdit.setPlaceholderText(_translate("Form", "search..."))

from toolset.rcc import resources_rc_pyqt5
