name: Compile and Test PyKotor

on: [push]

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # Disable automatic cancellation of other jobs
      matrix:
        os: [windows-2019, ubuntu-20.04, macos-12]
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11', '3.12', '3.13.0-alpha.4']
        architecture: ['x86', 'x64']
        exclude:
          # unix x86 is definitely not supported.
          - os: ubuntu-20.04
            architecture: x86
          - os: macos-12
            architecture: x86
    outputs:
      matrix-os: ${{ toJson(matrix.os) }}
      matrix-python-version: ${{ toJson(matrix.python-version) }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}

    - name: Setup python venvs
      run: |  # create the venv early to work around an issue with the matrix runners' concurrency
        python -m venv .venv_${{ matrix.os }}_${{ matrix.python-version }}_${{ matrix.architecture }}
        python -m venv .venv_holopatcher_${{ matrix.os }}_${{ matrix.python-version }}_${{ matrix.architecture }}
        python -m venv .venv_toolset_${{ matrix.os }}_${{ matrix.python-version }}_${{ matrix.architecture }}
        python -m venv .venv_guiduplicator_${{ matrix.os }}_${{ matrix.python-version }}_${{ matrix.architecture }}
        python -m venv .venv_kotordiff_${{ matrix.os }}_${{ matrix.python-version }}_${{ matrix.architecture }}
        python -m venv .venv_batchpatcher_${{ matrix.os }}_${{ matrix.python-version }}_${{ matrix.architecture }}
      shell: pwsh

    - name: Set UPX download URL
      id: upx_setup
      run: |
        if ("${{ runner.os }}" -eq "Windows") {
          echo "::set-output name=build::no"
          if ("${{ matrix.architecture }}" -eq "x86") {
            echo "::set-output name=url::https://github.com/upx/upx/releases/download/v4.2.2/upx-4.2.2-win32.zip"
          } else {
            echo "::set-output name=url::https://github.com/upx/upx/releases/download/v4.2.2/upx-4.2.2-win64.zip"
          }
        } elseif ("${{ runner.os }}" -eq "Linux") {
          echo "::set-output name=build::no"
          echo "::set-output name=url::https://github.com/upx/upx/releases/download/v4.2.2/upx-4.2.2-amd64_linux.tar.xz"
        } elseif ("${{ runner.os }}" -eq "macOS") {
          echo "::set-output name=build::no"
          echo "::set-output name=url::https://github.com/upx/upx/releases/download/v3.96/upx-3.96-amd64_macosx.tar.xz"
        }
      shell: pwsh
  
    - name: Install build dependencies (macOS)
      if: runner.os == 'macOS' && steps.upx_setup.outputs.build == 'yes'
      run: |
        brew install ucl
        brew install zlib
      shell: bash

    - name: Download and prepare UPX
      run: |
        if ("${{ runner.os }}" -eq "Windows") {
          $ext = "zip"
          $stripComponents = ""
        } else {
          $ext = "tar.xz"
          $stripComponents = "--strip-components=1"
        }
        $url = "${{ steps.upx_setup.outputs.url }}"
        $outputPath = "upx.$ext"
        # Use curl instead of Invoke-WebRequest on macOS (workaround to a strange bug)
        if ("${{ runner.os }}" -eq "macOS") {
          curl -L $url -o $outputPath
        } else {
          Invoke-WebRequest -Uri $url -OutFile $outputPath
        }
        
        # Ensure the upx-dir directory exists
        New-Item -ItemType Directory -Force -Path "upx-dir" -ErrorAction SilentlyContinue
    
        if ($ext.ToLower() -eq "zip") {
          Expand-Archive -Path $outputPath -DestinationPath "upx-dir"
        } elseif ($stripComponents) {
          tar -xf $outputPath -C "upx-dir" $stripComponents
        } else {
          tar -xf $outputPath -C "upx-dir"
        }
        Get-Item $outputPath
      shell: pwsh
    

    - name: Build UPX (macOS)
      if: runner.os == 'macOS'
      run: |
        cd upx-4.2.2-src
        make all
        cd ..
        mkdir -p upx-dir
        cp upx-4.2.2-src/src/upx upx-dir/upx
      shell: bash

    - name: Set UPX directory path
      id: upx_dir
      run: |
        echo "::set-output name=path::$(pwd)/upx-dir"
      shell: bash

    - name: Install HoloPatcher dependencies
      run: |
        ./install_python_venv.ps1 -noprompt -venv_name .venv_holopatcher_${{ matrix.os }}_${{ matrix.python-version }}_${{ matrix.architecture }}
        pip install "pyinstaller==5.4" --prefer-binary
        ./compile/deps_holopatcher.ps1 -noprompt -venv_name .venv_holopatcher_${{ matrix.os }}_${{ matrix.python-version }}_${{ matrix.architecture }}
      shell: pwsh
      continue-on-error: true
    
    - name: Compile HoloPatcher
      run: |
        ./compile/compile_holopatcher.ps1 -noprompt -venv_name .venv_holopatcher_${{ matrix.os }}_${{ matrix.python-version }}_${{ matrix.architecture }} -upx_dir ${{ steps.upx_dir.outputs.path }}
      shell: pwsh
      continue-on-error: true

    - name: Install Holocron Toolset dependencies
      run: |
        ./install_python_venv.ps1 -noprompt -venv_name .venv_toolset_${{ matrix.os }}_${{ matrix.python-version }}_${{ matrix.architecture }}
        pip install "pyinstaller==5.4" --prefer-binary
        ./compile/deps_toolset.ps1 -noprompt -venv_name .venv_toolset_${{ matrix.os }}_${{ matrix.python-version }}_${{ matrix.architecture }}
      shell: pwsh
      continue-on-error: true

    - name: Compile Holocron Toolset
      run: |
        ./compile/compile_toolset.ps1 -noprompt -venv_name .venv_toolset_${{ matrix.os }}_${{ matrix.python-version }}_${{ matrix.architecture }} -upx_dir ${{ steps.upx_dir.outputs.path }}
      shell: pwsh
      continue-on-error: true

    - name: Install BatchPatcher dependencies
      run: |
        ./install_python_venv.ps1 -noprompt -venv_name .venv_batchpatcher_${{ matrix.os }}_${{ matrix.python-version }}_${{ matrix.architecture }}
        pip install "pyinstaller==5.4" --prefer-binary
        ./compile/deps_batchpatcher.ps1 -noprompt -venv_name .venv_batchpatcher_${{ matrix.os }}_${{ matrix.python-version }}_${{ matrix.architecture }}
      shell: pwsh
      continue-on-error: true

    - name: Compile BatchPatcher
      run: |
        ./compile/compile_batchpatcher.ps1 -noprompt -venv_name .venv_batchpatcher_${{ matrix.os }}_${{ matrix.python-version }}_${{ matrix.architecture }} -upx_dir ${{ steps.upx_dir.outputs.path }}
      shell: pwsh
      continue-on-error: true

    - name: Compile KotorDiff
      run: |
        ./install_python_venv.ps1 -noprompt -venv_name .venv_kotordiff_${{ matrix.os }}_${{ matrix.python-version }}_${{ matrix.architecture }}
        pip install "pyinstaller==5.4" --prefer-binary
        pip install -r Tools/KotorDiff/requirements.txt --prefer-binary
        ./compile/compile_kotordiff.ps1 -noprompt -venv_name .venv_kotordiff_${{ matrix.os }}_${{ matrix.python-version }}_${{ matrix.architecture }} -upx_dir ${{ steps.upx_dir.outputs.path }}
      shell: pwsh
      continue-on-error: true

    - name: Compile GUIDuplicator
      run: |
        ./install_python_venv.ps1 -noprompt -venv_name .venv_guiduplicator_${{ matrix.os }}_${{ matrix.python-version }}_${{ matrix.architecture }}
        pip install "pyinstaller==5.4" --prefer-binary
        pip install -r Tools/GuiDuplicator/requirements.txt --prefer-binary
        ./compile/compile_gui_duplicator.ps1 -noprompt -venv_name .venv_guiduplicator_${{ matrix.os }}_${{ matrix.python-version }}_${{ matrix.architecture }} -upx_dir ${{ steps.upx_dir.outputs.path }}
      shell: pwsh
      continue-on-error: true

    - name: Upload compiled binaries
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: publish_${{ matrix.os }}_${{ matrix.python-version }}_${{ matrix.architecture }}
        path: ./dist/**

    - name: Install MinGW with GCC >= 8.4 on Windows
      if: runner.os == 'Windows' && matrix.python-version == '3.13.0-alpha.4'
      run: |
        choco install mingw --version=8.4.0 -y
        echo "C:\tools\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      shell: pwsh

    - name: Install Meson
      if: matrix.python-version == '3.13.0-alpha.4' && (runner.os == 'Linux' || runner.os == 'macOS')
      run: |
        ./install_python_venv.ps1 -noprompt -venv_name .venv_${{ matrix.os }}_${{ matrix.python-version }}_${{ matrix.architecture }}
        python -m pip install numpy --only-binary :all: --upgrade
        python -m pip install meson --upgrade --prefer-binary
      shell: pwsh

    - name: Install development packages
      run: |
        ./install_python_venv.ps1 -noprompt -venv_name .venv_${{ matrix.os }}_${{ matrix.python-version }}_${{ matrix.architecture }}
        if ($env:python_version -ne "3.13.0-alpha.4" -or $env:RUNNER_OS -eq "Windows") {
          pip install -r requirements-dev.txt --prefer-binary
        }
        else {
          pip install -r requirements-dev-py313.txt --prefer-binary
        }
      shell: pwsh

    - name: Run all unittests/pytests
      run: |
        ./install_python_venv.ps1 -noprompt -venv_name .venv_${{ matrix.os }}_${{ matrix.python-version }}_${{ matrix.architecture }}
        python -m pytest tests -v -ra -o log_cli=true --capture=no --junitxml=pytest_report.xml --html=pytest_report.html --self-contained-html --tb=no --continue-on-collection-errors
      shell: pwsh
      continue-on-error: true

    - name: Upload Pytest Reports
      uses: actions/upload-artifact@v4
      if: always()  # Ensures this step runs even if the previous step fails
      with:
        name: pytest_report_${{ matrix.os }}_${{ matrix.python-version }}_${{ matrix.architecture }}
        path: |
          pytest_report.html
          pytest_report.xml

  update-readme:
    needs: build  # do not start this job until all 'build' jobs complete
    # always run regardless of whether any builds errored or not.
    if: always()
    runs-on: ubuntu-latest  # Or any other suitable runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: all_pytest_reports
          pattern: pytest_report_*

      - name: Extract and update README with custom test status badges
        shell: pwsh
        run: |
          # Git configuration and commit
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

          # Determine the branch that triggered the workflow
          $branchName = "${{ github.ref_name }}"
          $repository_owner = "${{ github.repository_owner }}"
          $repository_name = "${{ github.repository }}"
          $uniqueTempBranchName = "temp-branch-${{ github.run_id }}"

          $testsResultsPath = "tests/results"
          Remove-Item -Path $testsResultsPath -Recurse -Force -ErrorAction SilentlyContinue
          New-Item -ItemType Directory -Force -Path $testsResultsPath

          $OS_NAMES = @("windows-2019", "ubuntu-20.04", "macos-12")
          $PYTHON_VERSIONS = @('3.7', '3.8', '3.9', '3.10', '3.11', '3.12', '3.13.0-alpha.4')
          $ARCHITECTURES = @('x86', 'x64')

          $extractedReportsPath = "tests/results"
          New-Item -ItemType Directory -Force -Path $extractedReportsPath

          New-Item -ItemType Directory -Force -Path "./all_pytest_reports" -ErrorAction SilentlyContinue
          Get-ChildItem "./all_pytest_reports" -Filter *.zip | ForEach-Object {
            Expand-Archive -Path $_.FullName -DestinationPath $(Join-Path -Path $extractedReportsPath -ChildPath $_.BaseName) -Force
          }
          Remove-Item -Path "./all_pytest_reports" -Recurse -Force -ErrorAction SilentlyContinue

          git fetch
          git checkout -b $uniqueTempBranchName
          git add -A
          git commit -am "Upload test results"
          $commitSHA = git rev-parse HEAD

          $testResults = @{}

          Get-ChildItem $extractedReportsPath -Recurse -Filter pytest_report.xml | ForEach-Object {
            [xml]$TestResultsXml = Get-Content $_.FullName
            $totalTests = [int]$TestResultsXml.testsuites.testsuite.tests
            $failedTests = [int]$TestResultsXml.testsuites.testsuite.failures
            $errors = [int]$TestResultsXml.testsuites.testsuite.errors
            $passedTests = $totalTests - $failedTests - $errors

            $resultFilePathHtml = $_.FullName -replace '\.xml$', '.html'
            $relHtmlFilePath = Resolve-Path -Path $resultFilePathHtml -Relative
            if ($relHtmlFilePath.StartsWith(".\") -or $relHtmlFilePath.StartsWith("./")) {
              $cleanRelHtmlFilePath = $relHtmlFilePath.Substring(2)
            } else {
              $cleanRelHtmlFilePath = $relHtmlFilePath
            }
            $DetailsURL = "https://github.com/$repository_owner/$repository_name/blob/$commitSHA/$cleanRelHtmlFilePath"
            $key = $_.Directory.Name.Replace('pytest_report_', '').Replace('_', '-')
            Write-Host "KEY FOUND: '$key'"

            $testResults[$key] = @{
              Passed = $passedTests
              Failed = $failedTests + $errors
              Total  = $totalTests
              DetailsURL = $DetailsURL
            }
          }

          $ReadmePath = "./README.md"
          $ReadmeContent = Get-Content $ReadmePath -Raw

          $WindowsBadgeContent = ""
          $LinuxBadgeContent = ""
          $MacOSBadgeContent = ""

          $windowsBadgesStartPlaceholder = "<!-- WINDOWS-BADGES-START -->"
          $windowsBadgesEndPlaceholder = "<!-- WINDOWS-BADGES-END -->"
          $linuxBadgesStartPlaceholder = "<!-- LINUX-BADGES-START -->"
          $linuxBadgesEndPlaceholder = "<!-- LINUX-BADGES-END -->"
          $macosBadgesStartPlaceholder = "<!-- MACOS-BADGES-START -->"
          $macosBadgesEndPlaceholder = "<!-- MACOS-BADGES-END -->"

          function Replace-BadgeContent {
            param (
                [string]$readmeContent,
                [string]$badgeContent,
                [string]$startPlaceholder,
                [string]$endPlaceholder
            )

            $pattern = [regex]::Escape($startPlaceholder) + "(.|\n)*?" + [regex]::Escape($endPlaceholder)
            $replacement = $startPlaceholder + "`n" + $badgeContent + "`n" + $endPlaceholder
            return $readmeContent -replace $pattern, $replacement
          }

          foreach ($OS in $OS_NAMES) {
            foreach ($PYTHON_VERSION in $PYTHON_VERSIONS) {
              foreach ($ARCH in $ARCHITECTURES) {
                $key = "$OS-$PYTHON_VERSION-$ARCH"
                if ($testResults.ContainsKey($key)) {
                    $passedTests = $testResults[$key]['Passed']
                    $failedTests = $testResults[$key]['Failed']
                    $DetailsURL = $testResults[$key]['DetailsURL']
                    # Encode the label to replace spaces with underscores and URI-encode other special characters
                    $encodedKey = [System.Web.HttpUtility]::UrlEncode($key.Replace(' ', '_').Replace('-', '--'))
                    $BadgeURLPassed = "https://img.shields.io/badge/${encodedKey}_Passed-${passedTests}-brightgreen"
                    $BadgeURLFailed = "https://img.shields.io/badge/${encodedKey}_Failed-${failedTests}-red"
                    $BadgeMarkdown = "[![$key-Passing]($BadgeURLPassed)]($DetailsURL) [![$key-Failing]($BadgeURLFailed)]($DetailsURL)"

                } else {
                    Write-Host "No test results for '$key', must have failed, generating 'Build Failed' badge..."
                    $encodedKey = [System.Web.HttpUtility]::UrlEncode($key.Replace(' ', '_').Replace('-', '--'))
                    $BadgeURLBuildFailed = "https://img.shields.io/badge/${encodedKey}_Build_Failed-lightgrey"
                    $DetailsURL = "https://github.com/$repository_owner/$repository_name/blob/$commitSHA/$testsResultsPath/$key-Build_Failed.xml"
                    $BadgeMarkdown = "[![$key-Build_Failed]($BadgeURLBuildFailed)]($DetailsURL)"
                }

                switch ($OS) {
                    "windows-2019" { $WindowsBadgeContent += $BadgeMarkdown + " " }
                    "ubuntu-20.04" { $LinuxBadgeContent += $BadgeMarkdown + " " }
                    "macos-12" { $MacOSBadgeContent += $BadgeMarkdown + " " }
                }
              }
            }
          }

          $ReadmeContent = Replace-BadgeContent -readmeContent $ReadmeContent -badgeContent $WindowsBadgeContent.TrimEnd() -startPlaceholder $windowsBadgesStartPlaceholder -endPlaceholder $windowsBadgesEndPlaceholder
          $ReadmeContent = Replace-BadgeContent -readmeContent $ReadmeContent -badgeContent $LinuxBadgeContent.TrimEnd() -startPlaceholder $linuxBadgesStartPlaceholder -endPlaceholder $linuxBadgesEndPlaceholder
          $ReadmeContent = Replace-BadgeContent -readmeContent $ReadmeContent -badgeContent $MacOSBadgeContent.TrimEnd() -startPlaceholder $macosBadgesStartPlaceholder -endPlaceholder $macosBadgesEndPlaceholder

          Set-Content -Path $ReadmePath -Value $ReadmeContent

          git commit -am "Update README with custom test status badges"
          git checkout $branchName
          git merge --no-ff $uniqueTempBranchName
          git branch -d $uniqueTempBranchName
          git push origin $branchName
