name: Python 3.12 unittest

on: [push]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Run unittest on files in pykotor/tests
      run: |
        ./install_python_venv.ps1 -noprompt
        ./compile/compile_holopatcher.ps1 -noprompt
        pip install -r requirements-dev.txt
        python -m unittest discover -s tests -p 'test_*.py' -v
      shell: pwsh
